---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create custom whitelist groups
  include: custom-whitelist.yml
  when: squid_custom_whitelist is defined and squid_custom_whitelist

- name: install squid
  package: name={{ squid_package }} state=present update_cache=yes

- name: copy template
  template: src=squid.conf.j2 dest={{ squid_conf }} owner=root group=root mode=0644
  notify: restart squid
