---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create custom whitelist groups
  include: custom-whitelist.yml
  when: squid_custom_whitelist is defined

# Install RedHat-like
- include: squid-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Install Debian-like
- include: squid-Debian.yml
  when: ansible_os_family == 'Debian'
