---
- name: Converge
  hosts: all
  tasks:
    - name: include custom whitelist
      include_vars:
        file: custom_whitelist.yml
    - name: execute role
      include_role:
        name: stone-payments.squid
